### ISSUE TITLE
[BUG]: UART not working with VESC 6.0.2 and MKS 75200

### ISSUE THREAD

**Issue by patatman** [Luddi96/BREmote#5]
**Describe the bug**
When enabling UART I'm getting the error in the serial monitor: 
`Message Error`

For some reason UART won't work. I've soldered TX2 and RX2 to the corresponding RX2 and TX2 on the Bremote receiver, but it won't work.
I've now directly connected the battery to the Receiver so I can see the battery % anyway.

But UART would be intresting, since I can also monitor temperature. 

Any idea what it could be?
I've wired the TX to RX and RX to TX.
Baudrate is at 15200

**Comment by Luddi96** [comment]
Try connecting TX to TX, Rx to Rx. Please report back if that works.

**Comment by patatman** [comment]
Sorry I never responded, I fixed it by using the PPM.
So didn't get around resoldering it. You can close this if you'd like.
Won't be until the winter until I start switching components again

**Comment by Luddi96** [comment]
No problem. I will close and you can open a new one should the problem persist
